<template>
  <div>
    <PageHeader eyebrow="Administration" title="发布账号" description="每个平台可配置多个发布账号；Secret 留空时保持后端现有值。"><template #actions><el-button type="primary" @click="openCreate"><el-icon><Plus /></el-icon>新增账号</el-button></template></PageHeader>
    <section class="surface"><div class="toolbar"><div class="toolbar-group"><el-input v-model="keyword" clearable placeholder="搜索账号名称或标识" :prefix-icon="Search" style="width: 240px" @keyup.enter="applyFilters" @clear="applyFilters" /><el-select v-model="platformFilter" clearable placeholder="全部平台" style="width: 150px" @change="applyFilters"><el-option v-for="platform in platforms" :key="platform.id" :label="platform.name" :value="platform.id" /></el-select><el-button @click="applyFilters">筛选</el-button></div><span class="muted">共 {{ total }} 个账号</span></div>
      <DataState :loading="loading" :error="error" :empty="!accounts.length" empty-text="尚未配置发布账号" @retry="load"><el-button type="primary" @click="openCreate">新增账号</el-button><template #content><el-table :data="accounts"><el-table-column label="账号" min-width="210"><template #default="scope"><div class="item-title">{{ scope.row.name }}</div><div class="item-meta mono">{{ scope.row.account_identifier || '未设置标识' }}</div><div v-if="scope.row.ig_user_id" class="item-meta mono">IG User ID: {{ scope.row.ig_user_id }}</div></template></el-table-column><el-table-column label="平台" min-width="120"><template #default="scope">{{ platformName(scope.row.platform_id) }}</template></el-table-column><el-table-column label="Client ID" min-width="140"><template #default="scope"><span class="mono">{{ scope.row.client_id_masked || '未配置' }}</span></template></el-table-column><el-table-column label="Access Token" min-width="140"><template #default="scope"><span class="mono">{{ scope.row.access_token_masked || '未配置' }}</span></template></el-table-column><el-table-column label="Token 到期" min-width="160"><template #default="scope">{{ formatDate(scope.row.token_expires_at) }}</template></el-table-column><el-table-column label="状态" width="100"><template #default="scope"><el-switch v-model="scope.row.enabled" :loading="switchingId === scope.row.id" @change="toggle(scope.row)" /></template></el-table-column><el-table-column label="操作" width="150" fixed="right"><template #default="scope"><el-button text type="primary" @click="openEdit(scope.row)">编辑</el-button><el-button text type="danger" @click="remove(scope.row)">删除</el-button></template></el-table-column></el-table></template></DataState>
      <div v-if="total > pageSize" class="pagination-row"><el-pagination v-model:current-page="page" :page-size="pageSize" :total="total" layout="prev, pager, next" @current-change="load" /></div>
    </section>

    <el-dialog v-model="dialogOpen" :title="editingId ? '编辑发布账号' : '新增发布账号'" width="680px" destroy-on-close>
      <el-alert v-if="editingId" class="secret-note" type="info" show-icon :closable="false" title="安全字段不会自动回填；留空表示不修改现有 Secret。" />
      <el-form ref="formRef" :model="form" :rules="rules" label-position="top"><div class="form-grid"><el-form-item label="发布平台" prop="platform_id"><el-select v-model="form.platform_id" :disabled="Boolean(editingId)" style="width: 100%"><el-option v-for="platform in platforms" :key="platform.id" :label="platform.name" :value="platform.id" /></el-select></el-form-item><el-form-item label="账号名称" prop="name"><el-input v-model="form.name" /></el-form-item><el-form-item label="账号标识"><el-input v-model="form.account_identifier" /></el-form-item><el-form-item label="状态"><el-switch v-model="form.enabled" active-text="启用" inactive-text="停用" /></el-form-item><el-form-item v-if="isInstagramAccount" label="Instagram User ID（IG 用户编号）" prop="ig_user_id" class="span-2" required><el-input v-model="form.ig_user_id" placeholder="例如：17841400000000000（不是 @用户名）" /></el-form-item><el-form-item label="Client ID"><el-input v-model="form.client_id" :placeholder="secretPlaceholder('client_id')" /></el-form-item><el-form-item label="Client Secret"><el-input v-model="form.client_secret" type="password" show-password :placeholder="secretPlaceholder('client_secret')" autocomplete="new-password" /></el-form-item><el-form-item label="Access Token"><el-input v-model="form.access_token" type="password" show-password :placeholder="secretPlaceholder('access_token')" autocomplete="new-password" /></el-form-item><el-form-item label="Refresh Token"><el-input v-model="form.refresh_token" type="password" show-password :placeholder="secretPlaceholder('refresh_token')" autocomplete="new-password" /></el-form-item><el-form-item label="Token 过期时间" class="span-2"><el-date-picker v-model="form.token_expires_at" type="datetime" value-format="YYYY-MM-DDTHH:mm:ssZ" placeholder="选择过期时间" style="width: 100%" /></el-form-item><el-form-item label="其他配置（JSON）" class="span-2"><el-input v-model="extraConfigText" class="json-editor" type="textarea" :rows="4" spellcheck="false" placeholder='{"simulate_result":"success"}' /></el-form-item></div></el-form>
      <template #footer><el-button @click="dialogOpen = false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存账号</el-button></template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'; import { Plus, Search } from '@element-plus/icons-vue'; import { ElMessage, ElMessageBox, type FormInstance, type FormRules } from 'element-plus'; import PageHeader from '@/components/PageHeader.vue'; import DataState from '@/components/DataState.vue'; import { createAccount, deleteAccount, getAccounts, getAdminPlatforms, updateAccount } from '@/api/platforms'; import type { PublishAccount, PublishAccountInput, PublishPlatform } from '@/types/platform'; import { formatDate } from '@/utils/format'; import { getErrorMessage } from '@/utils/errors'
const accounts = ref<PublishAccount[]>([]); const platforms = ref<PublishPlatform[]>([]); const loading = ref(true); const saving = ref(false); const error = ref(''); const keyword = ref(''); const platformFilter = ref(''); const page = ref(1); const pageSize = 20; const total = ref(0); const switchingId = ref(''); const dialogOpen = ref(false); const editingId = ref(''); const formRef = ref<FormInstance>(); const masked = reactive<Record<string, string>>({})
const extraConfigText = ref('{}')
const form = reactive<PublishAccountInput>({ platform_id: '', name: '', account_identifier: '', ig_user_id: '', enabled: true, client_id: '', client_secret: '', access_token: '', refresh_token: '', token_expires_at: '' })
const isInstagramAccount = computed(() => platforms.value.find((item) => item.id === form.platform_id)?.code.toLowerCase() === 'instagram')
const rules: FormRules<PublishAccountInput> = { platform_id: [{ required: true, message: '请选择发布平台', trigger: 'change' }], name: [{ required: true, message: '请输入账号名称', trigger: 'blur' }] }
function platformName(id: string) { return platforms.value.find((item) => item.id === id)?.name ?? id }
async function load() { loading.value = true; error.value = ''; try { const result = await getAccounts({ page: page.value, page_size: pageSize, keyword: keyword.value || undefined, platform_id: platformFilter.value || undefined }); accounts.value = result.items; total.value = result.total } catch (reason) { error.value = getErrorMessage(reason, '账号列表加载失败') } finally { loading.value = false } }
function applyFilters() { page.value = 1; load() }
function resetForm() { Object.assign(form, { platform_id: '', name: '', account_identifier: '', ig_user_id: '', enabled: true, client_id: '', client_secret: '', access_token: '', refresh_token: '', token_expires_at: '' }); extraConfigText.value = '{}'; Object.keys(masked).forEach((key) => { delete masked[key] }) }
function openCreate() { editingId.value = ''; resetForm(); dialogOpen.value = true }
function openEdit(account: PublishAccount) { editingId.value = account.id; resetForm(); const legacyIgUserId = account.extra_config?.ig_user_id; Object.assign(form, { platform_id: account.platform_id, name: account.name, account_identifier: account.account_identifier ?? '', ig_user_id: account.ig_user_id ?? (typeof legacyIgUserId === 'string' || typeof legacyIgUserId === 'number' ? String(legacyIgUserId) : ''), enabled: account.enabled, token_expires_at: account.token_expires_at ?? '' }); extraConfigText.value = JSON.stringify(account.extra_config ?? {}, null, 2); Object.assign(masked, { client_id: account.client_id_masked ?? '', client_secret: account.client_secret_masked ?? '', access_token: account.access_token_masked ?? '', refresh_token: account.refresh_token_masked ?? '' }); dialogOpen.value = true }
function secretPlaceholder(key: string) { return masked[key] ? `当前值：${masked[key]}；留空不修改` : '未配置' }
async function save() { if (isInstagramAccount.value && !form.ig_user_id?.trim()) { ElMessage.warning('请填写 Instagram User ID（不是 @用户名）'); return } if (!(await formRef.value?.validate().catch(() => false))) return; saving.value = true; try { let extraConfig: Record<string, unknown>; try { extraConfig = JSON.parse(extraConfigText.value) as Record<string, unknown> } catch { throw new Error('其他配置必须是有效 JSON') } const payload = { ...Object.fromEntries(Object.entries(form).filter(([, value]) => value !== '')), extra_config: extraConfig } as unknown as PublishAccountInput; if (editingId.value) await updateAccount(editingId.value, payload); else await createAccount(payload); ElMessage.success('发布账号已保存'); dialogOpen.value = false; await load() } catch (reason) { ElMessage.error(getErrorMessage(reason, '账号保存失败')) } finally { saving.value = false } }
async function toggle(account: PublishAccount) { switchingId.value = account.id; try { await updateAccount(account.id, { enabled: account.enabled }); ElMessage.success('账号状态已更新') } catch (reason) { account.enabled = !account.enabled; ElMessage.error(getErrorMessage(reason, '状态更新失败')) } finally { switchingId.value = '' } }
async function remove(account: PublishAccount) { try { await ElMessageBox.confirm(`确定删除发布账号“${account.name}”？`, '删除账号', { type: 'warning', confirmButtonText: '确认删除' }); await deleteAccount(account.id); ElMessage.success('账号已删除'); await load() } catch (reason) { if (reason !== 'cancel' && reason !== 'close') ElMessage.error(getErrorMessage(reason, '删除失败')) } }
onMounted(async () => { getAdminPlatforms({ page: 1, page_size: 100 }).then((result) => { platforms.value = result.items }).catch(() => undefined); await load() })
</script>
