<template>
  <div>
    <PageHeader :eyebrow="t('admin.eyebrow')" :title="t('admin.accountsTitle')" :description="t('admin.accountsIntro')"><template #actions><el-button type="primary" @click="openCreate"><el-icon><Plus /></el-icon>{{ t('admin.addAccount') }}</el-button></template></PageHeader>
    <section class="surface"><div class="toolbar"><div class="toolbar-group"><el-input v-model="keyword" clearable :placeholder="t('admin.searchAccount')" :prefix-icon="Search" style="width: 240px" @keyup.enter="applyFilters" @clear="applyFilters" /><el-select v-model="platformFilter" clearable :placeholder="t('publish.allPlatforms')" style="width: 150px" @change="applyFilters"><el-option v-for="platform in platforms" :key="platform.id" :label="platform.name" :value="platform.id" /></el-select><el-button @click="applyFilters">{{ t('common.filter') }}</el-button></div><span class="muted">{{ t('admin.totalAccounts', { count: total }) }}</span></div>
      <DataState :loading="loading" :error="error" :empty="!accounts.length" :empty-text="t('admin.noAccounts')" @retry="load"><el-button type="primary" @click="openCreate">{{ t('admin.addAccount') }}</el-button><template #content><el-table :data="accounts"><el-table-column :label="t('common.account')" min-width="210"><template #default="scope"><div class="item-title">{{ scope.row.name }}</div><div class="item-meta mono">{{ scope.row.account_identifier || t('common.notSet') }}</div><div v-if="scope.row.ig_user_id" class="item-meta mono">{{ t('admin.instagramUserId') }}: {{ scope.row.ig_user_id }}</div></template></el-table-column><el-table-column :label="t('common.platform')" min-width="120"><template #default="scope">{{ platformName(scope.row.platform_id) }}</template></el-table-column><el-table-column :label="t('common.clientId')" min-width="140"><template #default="scope"><span class="mono">{{ scope.row.client_id_masked || t('common.notConfigured') }}</span></template></el-table-column><el-table-column :label="t('common.accessToken')" min-width="140"><template #default="scope"><span class="mono">{{ scope.row.access_token_masked || t('common.notConfigured') }}</span></template></el-table-column><el-table-column :label="t('admin.tokenExpires')" min-width="160"><template #default="scope">{{ formatDate(scope.row.token_expires_at) }}</template></el-table-column><el-table-column :label="t('common.status')" width="100"><template #default="scope"><el-switch v-model="scope.row.enabled" :loading="switchingId === scope.row.id" @change="toggle(scope.row)" /></template></el-table-column><el-table-column :label="t('common.actions')" width="160" fixed="right"><template #default="scope"><el-button text type="primary" @click="openEdit(scope.row)">{{ t('common.edit') }}</el-button><el-button text type="danger" @click="remove(scope.row)">{{ t('common.delete') }}</el-button></template></el-table-column></el-table></template></DataState>
      <div v-if="total > pageSize" class="pagination-row"><el-pagination v-model:current-page="page" :page-size="pageSize" :total="total" layout="prev, pager, next" @current-change="load" /></div>
    </section>

    <el-dialog v-model="dialogOpen" :title="t(editingId ? 'admin.editAccount' : 'admin.addAccountTitle')" width="680px" destroy-on-close>
      <el-alert v-if="editingId" class="secret-note" type="info" show-icon :closable="false" :title="t('admin.secretKeepNotice')" />
      <el-form ref="formRef" :model="form" :rules="rules" label-position="top"><div class="form-grid"><el-form-item :label="t('routes.platforms')" prop="platform_id"><el-select v-model="form.platform_id" :disabled="Boolean(editingId)" style="width: 100%"><el-option v-for="platform in platforms" :key="platform.id" :label="platform.name" :value="platform.id" /></el-select></el-form-item><el-form-item :label="t('admin.accountName')" prop="name"><el-input v-model="form.name" /></el-form-item><el-form-item :label="t('admin.accountIdentifier')"><el-input v-model="form.account_identifier" /></el-form-item><el-form-item :label="t('common.status')"><el-switch v-model="form.enabled" :active-text="t('common.enabled')" :inactive-text="t('common.disabled')" /></el-form-item><el-form-item v-if="isInstagramAccount" :label="t('admin.instagramUserId')" prop="ig_user_id" class="span-2" required><el-input v-model="form.ig_user_id" :placeholder="t('admin.instagramIdPlaceholder')" /></el-form-item><el-form-item :label="t('common.clientId')"><el-input v-model="form.client_id" :placeholder="secretPlaceholder('client_id')" /></el-form-item><el-form-item :label="t('common.clientSecret')"><el-input v-model="form.client_secret" type="password" show-password :placeholder="secretPlaceholder('client_secret')" autocomplete="new-password" /></el-form-item><el-form-item :label="t('common.accessToken')"><el-input v-model="form.access_token" type="password" show-password :placeholder="secretPlaceholder('access_token')" autocomplete="new-password" /></el-form-item><el-form-item :label="t('common.refreshToken')"><el-input v-model="form.refresh_token" type="password" show-password :placeholder="secretPlaceholder('refresh_token')" autocomplete="new-password" /></el-form-item><el-form-item :label="t('admin.tokenExpiry')" class="span-2"><el-date-picker v-model="form.token_expires_at" type="datetime" value-format="YYYY-MM-DDTHH:mm:ssZ" :placeholder="t('admin.chooseExpiry')" style="width: 100%" /></el-form-item><el-form-item :label="t('admin.extraJson')" class="span-2"><el-input v-model="extraConfigText" class="json-editor" type="textarea" :rows="4" spellcheck="false" placeholder='{"simulate_result":"success"}' /></el-form-item></div></el-form>
      <template #footer><el-button @click="dialogOpen = false">{{ t('common.cancel') }}</el-button><el-button type="primary" :loading="saving" @click="save">{{ t('admin.saveAccount') }}</el-button></template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'; import { Plus, Search } from '@element-plus/icons-vue'; import { ElMessage, ElMessageBox, type FormInstance, type FormRules } from 'element-plus'; import PageHeader from '@/components/PageHeader.vue'; import DataState from '@/components/DataState.vue'; import { createAccount, deleteAccount, getAccounts, getAdminPlatforms, updateAccount } from '@/api/platforms'; import type { PublishAccount, PublishAccountInput, PublishPlatform } from '@/types/platform'; import { formatDate } from '@/utils/format'; import { getErrorMessage } from '@/utils/errors'
import { useI18n } from 'vue-i18n'
const accounts = ref<PublishAccount[]>([]); const platforms = ref<PublishPlatform[]>([]); const loading = ref(true); const saving = ref(false); const error = ref(''); const keyword = ref(''); const platformFilter = ref(''); const page = ref(1); const pageSize = 20; const total = ref(0); const switchingId = ref(''); const dialogOpen = ref(false); const editingId = ref(''); const formRef = ref<FormInstance>(); const masked = reactive<Record<string, string>>({})
const { t } = useI18n()
const extraConfigText = ref('{}')
const form = reactive<PublishAccountInput>({ platform_id: '', name: '', account_identifier: '', ig_user_id: '', enabled: true, client_id: '', client_secret: '', access_token: '', refresh_token: '', token_expires_at: '' })
const isInstagramAccount = computed(() => platforms.value.find((item) => item.id === form.platform_id)?.code.toLowerCase() === 'instagram')
const rules = computed<FormRules<PublishAccountInput>>(() => ({ platform_id: [{ required: true, message: t('admin.platformRequired'), trigger: 'change' }], name: [{ required: true, message: t('admin.accountNameRequired'), trigger: 'blur' }] }))
function platformName(id: string) { return platforms.value.find((item) => item.id === id)?.name ?? id }
async function load() { loading.value = true; error.value = ''; try { const result = await getAccounts({ page: page.value, page_size: pageSize, keyword: keyword.value || undefined, platform_id: platformFilter.value || undefined }); accounts.value = result.items; total.value = result.total } catch (reason) { error.value = getErrorMessage(reason, t('admin.accountListFailed')) } finally { loading.value = false } }
function applyFilters() { page.value = 1; load() }
function resetForm() { Object.assign(form, { platform_id: '', name: '', account_identifier: '', ig_user_id: '', enabled: true, client_id: '', client_secret: '', access_token: '', refresh_token: '', token_expires_at: '' }); extraConfigText.value = '{}'; Object.keys(masked).forEach((key) => { delete masked[key] }) }
function openCreate() { editingId.value = ''; resetForm(); dialogOpen.value = true }
function openEdit(account: PublishAccount) { editingId.value = account.id; resetForm(); const legacyIgUserId = account.extra_config?.ig_user_id; Object.assign(form, { platform_id: account.platform_id, name: account.name, account_identifier: account.account_identifier ?? '', ig_user_id: account.ig_user_id ?? (typeof legacyIgUserId === 'string' || typeof legacyIgUserId === 'number' ? String(legacyIgUserId) : ''), enabled: account.enabled, token_expires_at: account.token_expires_at ?? '' }); extraConfigText.value = JSON.stringify(account.extra_config ?? {}, null, 2); Object.assign(masked, { client_id: account.client_id_masked ?? '', client_secret: account.client_secret_masked ?? '', access_token: account.access_token_masked ?? '', refresh_token: account.refresh_token_masked ?? '' }); dialogOpen.value = true }
function secretPlaceholder(key: string) { return masked[key] ? t('common.currentValueKeep', { value: masked[key] }) : t('common.notConfigured') }
async function save() { if (isInstagramAccount.value && !form.ig_user_id?.trim()) { ElMessage.warning(t('admin.instagramIdRequired')); return } if (!(await formRef.value?.validate().catch(() => false))) return; saving.value = true; try { let extraConfig: Record<string, unknown>; try { extraConfig = JSON.parse(extraConfigText.value) as Record<string, unknown> } catch { throw new Error(t('common.jsonInvalid')) } const payload = { ...Object.fromEntries(Object.entries(form).filter(([, value]) => value !== '')), extra_config: extraConfig } as unknown as PublishAccountInput; if (editingId.value) await updateAccount(editingId.value, payload); else await createAccount(payload); ElMessage.success(t('admin.accountSaved')); dialogOpen.value = false; await load() } catch (reason) { ElMessage.error(getErrorMessage(reason, t('admin.accountSaveFailed'))) } finally { saving.value = false } }
async function toggle(account: PublishAccount) { switchingId.value = account.id; try { await updateAccount(account.id, { enabled: account.enabled }); ElMessage.success(t('admin.accountStatusUpdated')) } catch (reason) { account.enabled = !account.enabled; ElMessage.error(getErrorMessage(reason, t('admin.statusUpdateFailed'))) } finally { switchingId.value = '' } }
async function remove(account: PublishAccount) { try { await ElMessageBox.confirm(t('admin.deleteAccountPrompt', { name: account.name }), t('admin.deleteAccountTitle'), { type: 'warning', confirmButtonText: t('common.confirmDelete'), cancelButtonText: t('common.cancel') }); await deleteAccount(account.id); ElMessage.success(t('admin.accountDeleted')); await load() } catch (reason) { if (reason !== 'cancel' && reason !== 'close') ElMessage.error(getErrorMessage(reason, t('video.deleteFailed'))) } }
onMounted(async () => { getAdminPlatforms({ page: 1, page_size: 100 }).then((result) => { platforms.value = result.items }).catch(() => undefined); await load() })
</script>
