<template>
  <div>
    <PageHeader :eyebrow="t('admin.eyebrow')" :title="t('admin.logsTitle')" :description="t('admin.logsIntro')" />
    <section class="surface"><div class="toolbar"><div class="toolbar-group"><el-input v-model="filters.keyword" clearable :placeholder="t('admin.searchLog')" :prefix-icon="Search" style="width: 230px" @keyup.enter="applyFilters" @clear="applyFilters" /><el-select v-model="filters.result" clearable :placeholder="t('admin.allResults')" style="width: 130px" @change="applyFilters"><el-option :label="t('common.success')" value="success" /><el-option :label="t('common.failed')" value="failed" /></el-select><el-date-picker v-model="filters.dates" type="daterange" value-format="YYYY-MM-DD" :start-placeholder="t('publish.startDate')" :end-placeholder="t('publish.endDate')" :range-separator="t('publish.rangeSeparator')" @change="applyFilters" /><el-button @click="applyFilters">{{ t('common.filter') }}</el-button></div><span class="muted">{{ t('admin.totalLogs', { count: total }) }}</span></div>
      <DataState :loading="loading" :error="error" :empty="!logs.length" :empty-text="t('admin.noLogs')" @retry="load"><template #content><el-table :data="logs"><el-table-column :label="t('common.time')" min-width="165"><template #default="scope">{{ formatDate(scope.row.created_at) }}</template></el-table-column><el-table-column :label="t('common.user')" min-width="130"><template #default="scope">{{ scope.row.username || scope.row.user_id || t('common.system') }}</template></el-table-column><el-table-column prop="action" :label="t('admin.actionType')" min-width="150"><template #default="scope"><span class="mono">{{ scope.row.action }}</span></template></el-table-column><el-table-column :label="t('admin.resource')" min-width="180"><template #default="scope"><div>{{ scope.row.resource_type }}</div><div class="item-meta mono">{{ scope.row.resource_id || '—' }}</div></template></el-table-column><el-table-column :label="t('common.result')" width="100"><template #default="scope"><el-tag :type="scope.row.result === 'success' ? 'success' : 'danger'">{{ t(`status.${scope.row.result}`) }}</el-tag></template></el-table-column><el-table-column prop="ip_address" :label="t('admin.ip')" min-width="130"><template #default="scope"><span class="mono">{{ scope.row.ip_address || '—' }}</span></template></el-table-column><el-table-column :label="t('admin.errorMessage')" min-width="220"><template #default="scope"><span :class="scope.row.error_message ? 'danger-text' : 'muted'">{{ scope.row.error_message || '—' }}</span></template></el-table-column></el-table></template></DataState>
      <div v-if="total > pageSize" class="pagination-row"><el-pagination v-model:current-page="page" :page-size="pageSize" :total="total" layout="prev, pager, next" @current-change="load" /></div>
    </section>
  </div>
</template>

<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'; import { Search } from '@element-plus/icons-vue'; import PageHeader from '@/components/PageHeader.vue'; import DataState from '@/components/DataState.vue'; import { getOperationLogs } from '@/api/logs'; import type { OperationLog } from '@/types/log'; import { formatDate } from '@/utils/format'; import { getErrorMessage } from '@/utils/errors'
import { useI18n } from 'vue-i18n'
const logs = ref<OperationLog[]>([]); const loading = ref(true); const error = ref(''); const page = ref(1); const pageSize = 20; const total = ref(0); const filters = reactive<{ keyword: string; result: string; dates: string[] }>({ keyword: '', result: '', dates: [] })
const { t } = useI18n()
async function load() { loading.value = true; error.value = ''; try { const result = await getOperationLogs({ page: page.value, page_size: pageSize, keyword: filters.keyword || undefined, result: filters.result || undefined, date_from: filters.dates[0], date_to: filters.dates[1] }); logs.value = result.items; total.value = result.total } catch (reason) { error.value = getErrorMessage(reason, t('admin.logsLoadFailed')) } finally { loading.value = false } }
function applyFilters() { page.value = 1; load() }
onMounted(load)
</script>
