<template>
  <div>
    <PageHeader eyebrow="Administration" title="操作日志" description="只读查看登录、生成、发布和系统配置操作的执行结果。" />
    <section class="surface"><div class="toolbar"><div class="toolbar-group"><el-input v-model="filters.keyword" clearable placeholder="用户、操作或资源" :prefix-icon="Search" style="width: 230px" @keyup.enter="applyFilters" @clear="applyFilters" /><el-select v-model="filters.result" clearable placeholder="全部结果" style="width: 130px" @change="applyFilters"><el-option label="成功" value="success" /><el-option label="失败" value="failed" /></el-select><el-date-picker v-model="filters.dates" type="daterange" value-format="YYYY-MM-DD" start-placeholder="开始日期" end-placeholder="结束日期" range-separator="至" @change="applyFilters" /><el-button @click="applyFilters">筛选</el-button></div><span class="muted">共 {{ total }} 条日志</span></div>
      <DataState :loading="loading" :error="error" :empty="!logs.length" empty-text="没有符合条件的操作日志" @retry="load"><template #content><el-table :data="logs"><el-table-column label="时间" min-width="165"><template #default="scope">{{ formatDate(scope.row.created_at) }}</template></el-table-column><el-table-column label="用户" min-width="130"><template #default="scope">{{ scope.row.username || scope.row.user_id || '系统' }}</template></el-table-column><el-table-column prop="action" label="操作类型" min-width="150"><template #default="scope"><span class="mono">{{ scope.row.action }}</span></template></el-table-column><el-table-column label="资源" min-width="180"><template #default="scope"><div>{{ scope.row.resource_type }}</div><div class="item-meta mono">{{ scope.row.resource_id || '—' }}</div></template></el-table-column><el-table-column label="结果" width="100"><template #default="scope"><el-tag :type="scope.row.result === 'success' ? 'success' : 'danger'">{{ scope.row.result === 'success' ? '成功' : '失败' }}</el-tag></template></el-table-column><el-table-column prop="ip_address" label="IP" min-width="130"><template #default="scope"><span class="mono">{{ scope.row.ip_address || '—' }}</span></template></el-table-column><el-table-column label="错误信息" min-width="220"><template #default="scope"><span :class="scope.row.error_message ? 'danger-text' : 'muted'">{{ scope.row.error_message || '—' }}</span></template></el-table-column></el-table></template></DataState>
      <div v-if="total > pageSize" class="pagination-row"><el-pagination v-model:current-page="page" :page-size="pageSize" :total="total" layout="prev, pager, next" @current-change="load" /></div>
    </section>
  </div>
</template>

<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'; import { Search } from '@element-plus/icons-vue'; import PageHeader from '@/components/PageHeader.vue'; import DataState from '@/components/DataState.vue'; import { getOperationLogs } from '@/api/logs'; import type { OperationLog } from '@/types/log'; import { formatDate } from '@/utils/format'; import { getErrorMessage } from '@/utils/errors'
const logs = ref<OperationLog[]>([]); const loading = ref(true); const error = ref(''); const page = ref(1); const pageSize = 20; const total = ref(0); const filters = reactive<{ keyword: string; result: string; dates: string[] }>({ keyword: '', result: '', dates: [] })
async function load() { loading.value = true; error.value = ''; try { const result = await getOperationLogs({ page: page.value, page_size: pageSize, keyword: filters.keyword || undefined, result: filters.result || undefined, date_from: filters.dates[0], date_to: filters.dates[1] }); logs.value = result.items; total.value = result.total } catch (reason) { error.value = getErrorMessage(reason, '操作日志加载失败') } finally { loading.value = false } }
function applyFilters() { page.value = 1; load() }
onMounted(load)
</script>
