<template>
  <div>
    <PageHeader eyebrow="Administration" title="视频模型" description="模型能力决定制作页可用的时长、比例和分辨率；密钥不会在列表中明文返回。"><template #actions><el-button type="primary" @click="$router.push('/admin/models/new')"><el-icon><Plus /></el-icon>新增模型</el-button></template></PageHeader>
    <section class="surface"><div class="toolbar"><div class="toolbar-group"><el-input v-model="keyword" clearable placeholder="搜索名称、编码或厂商" :prefix-icon="Search" style="width: 260px" @keyup.enter="applySearch" @clear="applySearch" /><el-button @click="applySearch">搜索</el-button></div><span class="muted">共 {{ total }} 个模型</span></div>
      <DataState :loading="loading" :error="error" :empty="!models.length" empty-text="尚未配置视频模型" @retry="load"><el-button type="primary" @click="$router.push('/admin/models/new')">新增模型</el-button><template #content><el-table :data="models"><el-table-column label="模型" min-width="220"><template #default="scope"><div class="item-title">{{ scope.row.name }}</div><div class="item-meta mono">{{ scope.row.code }}</div></template></el-table-column><el-table-column prop="provider" label="厂商" min-width="130"><template #default="scope">{{ scope.row.provider || '—' }}</template></el-table-column><el-table-column label="生成能力" min-width="190"><template #default="scope"><div class="capability-tags"><el-tag size="small" :type="scope.row.supports_text_to_video ? 'success' : 'info'">文生视频</el-tag><el-tag size="small" :type="scope.row.supports_image_to_video ? 'success' : 'info'">图生视频</el-tag></div></template></el-table-column><el-table-column label="API Key" min-width="140"><template #default="scope"><span class="mono">{{ scope.row.api_key_masked || '未配置' }}</span></template></el-table-column><el-table-column label="状态" width="100"><template #default="scope"><el-switch v-model="scope.row.enabled" :loading="switchingId === scope.row.id" @change="toggle(scope.row)" /></template></el-table-column><el-table-column label="操作" width="150" fixed="right"><template #default="scope"><el-button text type="primary" @click="$router.push(`/admin/models/${scope.row.id}`)">配置</el-button><el-button text type="danger" @click="remove(scope.row)">删除</el-button></template></el-table-column></el-table></template></DataState>
      <div v-if="total > pageSize" class="pagination-row"><el-pagination v-model:current-page="page" :page-size="pageSize" :total="total" layout="prev, pager, next" @current-change="load" /></div>
    </section>
  </div>
</template>

<script setup lang="ts">
import { onMounted, ref } from 'vue'; import { Plus, Search } from '@element-plus/icons-vue'; import { ElMessage, ElMessageBox } from 'element-plus'
import PageHeader from '@/components/PageHeader.vue'; import DataState from '@/components/DataState.vue'; import { deleteVideoModel, getAdminVideoModels, updateVideoModel } from '@/api/models'; import type { VideoModelOption } from '@/types/video-model'; import { getErrorMessage } from '@/utils/errors'
const models = ref<VideoModelOption[]>([]); const loading = ref(true); const error = ref(''); const keyword = ref(''); const page = ref(1); const pageSize = 20; const total = ref(0); const switchingId = ref('')
async function load() { loading.value = true; error.value = ''; try { const result = await getAdminVideoModels({ page: page.value, page_size: pageSize, keyword: keyword.value || undefined }); models.value = result.items; total.value = result.total } catch (reason) { error.value = getErrorMessage(reason, '模型列表加载失败') } finally { loading.value = false } }
function applySearch() { page.value = 1; load() }
async function toggle(model: VideoModelOption) { switchingId.value = model.id; try { await updateVideoModel(model.id, { enabled: model.enabled }); ElMessage.success('模型状态已更新') } catch (reason) { model.enabled = !model.enabled; ElMessage.error(getErrorMessage(reason, '状态更新失败')) } finally { switchingId.value = '' } }
async function remove(model: VideoModelOption) { try { await ElMessageBox.confirm(`确定删除模型“${model.name}”？`, '删除模型', { type: 'warning', confirmButtonText: '确认删除' }); await deleteVideoModel(model.id); ElMessage.success('模型已删除'); await load() } catch (reason) { if (reason !== 'cancel' && reason !== 'close') ElMessage.error(getErrorMessage(reason, '删除失败')) } }
onMounted(load)
</script>
