<template>
  <div>
    <PageHeader eyebrow="Model configuration" :title="isNew ? '新增视频模型' : '编辑视频模型'" description="连接信息与模型能力由后端适配层使用，前端不直接请求模型厂商。"><template #actions><el-button @click="$router.push('/admin/models')">返回模型列表</el-button></template></PageHeader>
    <DataState :loading="loading" :error="error" @retry="load"><template #content>
      <el-form ref="formRef" :model="form" :rules="rules" label-position="top">
        <div class="content-grid">
          <section class="surface"><div class="surface-header"><div><h2>基础与连接信息</h2><p>Secret 留空表示不修改现有值</p></div></div><div class="surface-body"><el-alert class="secret-note" type="info" :closable="false" show-icon title="安全字段仅显示脱敏提示，完整值不会通过查询接口回填。" /><div class="form-grid"><el-form-item label="模型名称" prop="name"><el-input v-model="form.name" /></el-form-item><el-form-item label="模型编码" prop="code"><el-input v-model="form.code" class="mono" /></el-form-item><el-form-item label="厂商" prop="provider"><el-input v-model="form.provider" /></el-form-item><el-form-item label="Adapter Type" prop="adapter_type"><el-input v-model="form.adapter_type" class="mono" /></el-form-item><el-form-item label="Model ID"><el-input v-model="form.model_id" /></el-form-item><el-form-item label="API Base URL"><el-input v-model="form.api_base_url" /></el-form-item><el-form-item label="API Key" class="span-2 secret-field"><el-input v-model="form.api_key" type="password" show-password :placeholder="maskedPlaceholder" autocomplete="new-password" /></el-form-item><el-form-item label="超时时间（秒）"><el-input-number v-model="form.timeout_seconds" :min="1" :max="3600" controls-position="right" style="width: 100%" /></el-form-item><el-form-item label="状态"><el-switch v-model="form.enabled" active-text="启用" inactive-text="停用" /></el-form-item><el-form-item label="说明" class="span-2"><el-input v-model="form.description" type="textarea" :rows="3" /></el-form-item></div></div></section>
          <section class="surface"><div class="surface-header"><div><h2>模型能力</h2><p>这些选项将动态驱动视频制作表单</p></div></div><div class="surface-body"><el-form-item label="生成方式"><el-checkbox v-model="form.supports_text_to_video">文生视频</el-checkbox><el-checkbox v-model="form.supports_image_to_video">图生视频</el-checkbox></el-form-item><el-form-item label="支持时长（秒，以逗号分隔）"><el-input v-model="capabilityText.durations" placeholder="5, 10, 15" /></el-form-item><el-form-item label="支持比例（以逗号分隔）"><el-input v-model="capabilityText.aspect_ratios" placeholder="16:9, 9:16, 1:1" /></el-form-item><el-form-item label="支持分辨率（以逗号分隔）"><el-input v-model="capabilityText.resolutions" placeholder="720p, 1080p" /></el-form-item><el-form-item label="最多参考图"><el-input-number v-model="form.max_images" :min="0" :max="20" style="width: 100%" /></el-form-item><el-form-item label="图片大小上限（MB）"><el-input-number v-model="form.max_image_size_mb" :min="1" :max="200" style="width: 100%" /></el-form-item><el-form-item label="其他配置（JSON）"><el-input v-model="extraConfigText" class="json-editor" type="textarea" spellcheck="false" placeholder="{}" /></el-form-item></div></section>
        </div>
        <div class="editor-footer"><el-button @click="$router.push('/admin/models')">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存模型</el-button></div>
      </el-form>
    </template></DataState>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'; import { useRoute, useRouter } from 'vue-router'; import { ElMessage, type FormInstance, type FormRules } from 'element-plus'
import PageHeader from '@/components/PageHeader.vue'; import DataState from '@/components/DataState.vue'; import { createVideoModel, getAdminVideoModel, updateVideoModel } from '@/api/models'; import type { VideoModelInput } from '@/types/video-model'; import { getErrorMessage } from '@/utils/errors'
type FormModel = { name: string; code: string; provider: string; adapter_type: string; description: string; supports_text_to_video: boolean; supports_image_to_video: boolean; enabled: boolean; api_base_url: string; api_key: string; model_id: string; timeout_seconds: number; max_images: number; max_image_size_mb: number }
const route = useRoute(); const router = useRouter(); const id = String(route.params.id); const isNew = computed(() => id === 'new'); const formRef = ref<FormInstance>(); const loading = ref(!isNew.value); const saving = ref(false); const error = ref(''); const existingMasked = ref('')
const form = reactive<FormModel>({ name: '', code: '', provider: '', adapter_type: 'mock_video', description: '', supports_text_to_video: true, supports_image_to_video: false, enabled: true, api_base_url: '', api_key: '', model_id: '', timeout_seconds: 300, max_images: 1, max_image_size_mb: 10 })
const capabilityText = reactive({ durations: '', aspect_ratios: '', resolutions: '' }); const extraConfigText = ref('{}'); const maskedPlaceholder = computed(() => existingMasked.value ? `当前值：${existingMasked.value}；留空不修改` : '输入 API Key')
const rules: FormRules<FormModel> = { name: [{ required: true, message: '请输入模型名称', trigger: 'blur' }], code: [{ required: true, message: '请输入模型编码', trigger: 'blur' }], provider: [{ required: true, message: '请输入模型厂商', trigger: 'blur' }], adapter_type: [{ required: true, message: '请输入 Adapter Type', trigger: 'blur' }] }
function csv(value: string) { return value.split(',').map((item) => item.trim()).filter(Boolean) }
function buildPayload(): VideoModelInput { let extra: Record<string, unknown>; try { extra = JSON.parse(extraConfigText.value) as Record<string, unknown> } catch { throw new Error('其他配置必须是有效 JSON') } return { name: form.name, code: form.code, provider: form.provider, adapter_type: form.adapter_type, description: form.description, supports_text_to_video: form.supports_text_to_video, supports_image_to_video: form.supports_image_to_video, enabled: form.enabled, api_base_url: form.api_base_url, api_key: form.api_key || undefined, model_id: form.model_id, timeout_seconds: form.timeout_seconds, capabilities: { durations: csv(capabilityText.durations).map(Number).filter(Number.isFinite), aspect_ratios: csv(capabilityText.aspect_ratios), resolutions: csv(capabilityText.resolutions), max_images: form.max_images, max_image_size_mb: form.max_image_size_mb }, extra_config: extra } }
async function load() { if (isNew.value) { loading.value = false; return } loading.value = true; error.value = ''; try { const model = await getAdminVideoModel(id); Object.assign(form, { name: model.name, code: model.code, provider: model.provider ?? '', adapter_type: model.adapter_type ?? 'mock_video', description: model.description ?? '', supports_text_to_video: model.supports_text_to_video, supports_image_to_video: model.supports_image_to_video, enabled: model.enabled ?? true, api_base_url: model.api_base_url ?? '', api_key: '', model_id: model.model_id ?? '', timeout_seconds: model.timeout_seconds ?? 300, max_images: model.capabilities.max_images ?? 1, max_image_size_mb: model.capabilities.max_image_size_mb ?? 10 }); capabilityText.durations = model.capabilities.durations?.join(', ') ?? ''; capabilityText.aspect_ratios = model.capabilities.aspect_ratios?.join(', ') ?? ''; capabilityText.resolutions = model.capabilities.resolutions?.join(', ') ?? ''; extraConfigText.value = JSON.stringify(model.extra_config ?? {}, null, 2); existingMasked.value = model.api_key_masked ?? '' } catch (reason) { error.value = getErrorMessage(reason, '模型配置加载失败') } finally { loading.value = false } }
async function save() { if (!(await formRef.value?.validate().catch(() => false))) return; if (!form.supports_text_to_video && !form.supports_image_to_video) { ElMessage.error('至少启用一种生成方式'); return } saving.value = true; try { const payload = buildPayload(); if (isNew.value) await createVideoModel(payload); else await updateVideoModel(id, payload); ElMessage.success('模型配置已保存'); router.push('/admin/models') } catch (reason) { ElMessage.error(getErrorMessage(reason, '模型保存失败')) } finally { saving.value = false } }
onMounted(load)
</script>

<style scoped>.editor-footer { display: flex; justify-content: flex-end; gap: 10px; margin-top: 20px; padding: 18px 0; }</style>
