<template>
  <div>
    <PageHeader :eyebrow="t('admin.eyebrow')" :title="t('admin.modelsTitle')" :description="t('admin.modelsIntro')"><template #actions><el-button type="primary" @click="$router.push('/admin/models/new')"><el-icon><Plus /></el-icon>{{ t('admin.addModel') }}</el-button></template></PageHeader>
    <section class="surface"><div class="toolbar"><div class="toolbar-group"><el-input v-model="keyword" clearable :placeholder="t('admin.searchModel')" :prefix-icon="Search" style="width: 260px" @keyup.enter="applySearch" @clear="applySearch" /><el-button @click="applySearch">{{ t('common.search') }}</el-button></div><span class="muted">{{ t('admin.totalModels', { count: total }) }}</span></div>
      <DataState :loading="loading" :error="error" :empty="!models.length" :empty-text="t('admin.noModels')" @retry="load"><el-button type="primary" @click="$router.push('/admin/models/new')">{{ t('admin.addModel') }}</el-button><template #content><el-table :data="models"><el-table-column :label="t('common.model')" min-width="220"><template #default="scope"><div class="item-title">{{ scope.row.name }}</div><div class="item-meta mono">{{ scope.row.code }}</div></template></el-table-column><el-table-column prop="provider" :label="t('admin.provider')" min-width="130"><template #default="scope">{{ scope.row.provider || '—' }}</template></el-table-column><el-table-column :label="t('admin.capabilities')" min-width="210"><template #default="scope"><div class="capability-tags"><el-tag size="small" :type="scope.row.supports_text_to_video ? 'success' : 'info'">{{ t('generationType.text_to_video') }}</el-tag><el-tag size="small" :type="scope.row.supports_image_to_video ? 'success' : 'info'">{{ t('generationType.image_to_video') }}</el-tag></div></template></el-table-column><el-table-column :label="t('common.apiKey')" min-width="140"><template #default="scope"><span class="mono">{{ scope.row.api_key_masked || t('common.notConfigured') }}</span></template></el-table-column><el-table-column :label="t('common.status')" width="100"><template #default="scope"><el-switch v-model="scope.row.enabled" :loading="switchingId === scope.row.id" @change="toggle(scope.row)" /></template></el-table-column><el-table-column :label="t('common.actions')" width="160" fixed="right"><template #default="scope"><el-button text type="primary" @click="$router.push(`/admin/models/${scope.row.id}`)">{{ t('common.configure') }}</el-button><el-button text type="danger" @click="remove(scope.row)">{{ t('common.delete') }}</el-button></template></el-table-column></el-table></template></DataState>
      <div v-if="total > pageSize" class="pagination-row"><el-pagination v-model:current-page="page" :page-size="pageSize" :total="total" layout="prev, pager, next" @current-change="load" /></div>
    </section>
  </div>
</template>

<script setup lang="ts">
import { onMounted, ref } from 'vue'; import { Plus, Search } from '@element-plus/icons-vue'; import { ElMessage, ElMessageBox } from 'element-plus'
import { useI18n } from 'vue-i18n'
import PageHeader from '@/components/PageHeader.vue'; import DataState from '@/components/DataState.vue'; import { deleteVideoModel, getAdminVideoModels, updateVideoModel } from '@/api/models'; import type { VideoModelOption } from '@/types/video-model'; import { getErrorMessage } from '@/utils/errors'
const models = ref<VideoModelOption[]>([]); const loading = ref(true); const error = ref(''); const keyword = ref(''); const page = ref(1); const pageSize = 20; const total = ref(0); const switchingId = ref('')
const { t } = useI18n()
async function load() { loading.value = true; error.value = ''; try { const result = await getAdminVideoModels({ page: page.value, page_size: pageSize, keyword: keyword.value || undefined }); models.value = result.items; total.value = result.total } catch (reason) { error.value = getErrorMessage(reason, t('admin.modelListFailed')) } finally { loading.value = false } }
function applySearch() { page.value = 1; load() }
async function toggle(model: VideoModelOption) { switchingId.value = model.id; try { await updateVideoModel(model.id, { enabled: model.enabled }); ElMessage.success(t('admin.modelStatusUpdated')) } catch (reason) { model.enabled = !model.enabled; ElMessage.error(getErrorMessage(reason, t('admin.statusUpdateFailed'))) } finally { switchingId.value = '' } }
async function remove(model: VideoModelOption) { try { await ElMessageBox.confirm(t('admin.deleteModelPrompt', { name: model.name }), t('admin.deleteModelTitle'), { type: 'warning', confirmButtonText: t('common.confirmDelete'), cancelButtonText: t('common.cancel') }); await deleteVideoModel(model.id); ElMessage.success(t('admin.modelDeleted')); await load() } catch (reason) { if (reason !== 'cancel' && reason !== 'close') ElMessage.error(getErrorMessage(reason, t('video.deleteFailed'))) } }
onMounted(load)
</script>
