<template>
  <div>
    <PageHeader :eyebrow="t('routes.platformConfig')" :title="t(isNew ? 'admin.addPlatformTitle' : 'admin.editPlatformTitle')" :description="t('admin.platformEditorIntro')"><template #actions><el-button @click="$router.push('/admin/platforms')">{{ t('admin.backPlatformList') }}</el-button></template></PageHeader>
    <DataState :loading="loading" :error="error" @retry="load"><template #content><el-form ref="formRef" :model="form" :rules="rules" label-position="top"><div class="content-grid"><section class="surface"><div class="surface-header"><div><h2>{{ t('admin.platformInfo') }}</h2><p>{{ t('admin.platformInfoHint') }}</p></div></div><div class="surface-body"><div class="form-grid"><el-form-item :label="t('admin.platformName')" prop="name"><el-input v-model="form.name" /></el-form-item><el-form-item :label="t('admin.platformCode')" prop="code"><el-input v-model="form.code" class="mono" /></el-form-item><el-form-item :label="t('common.adapterType')" prop="adapter_type"><el-input v-model="form.adapter_type" class="mono" /></el-form-item><el-form-item :label="t('common.status')"><el-switch v-model="form.enabled" :active-text="t('common.enabled')" :inactive-text="t('common.disabled')" /></el-form-item><el-form-item :label="t('common.apiBaseUrl')" class="span-2"><el-input v-model="form.api_base_url" /></el-form-item><el-form-item :label="t('admin.platformDescription')" class="span-2"><el-input v-model="form.description" type="textarea" :rows="4" /></el-form-item></div></div></section><section class="surface"><div class="surface-header"><div><h2>{{ t('admin.fieldCapabilities') }}</h2><p>{{ t('admin.fieldCapabilitiesHint') }}</p></div></div><div class="surface-body"><el-alert type="info" :closable="false" show-icon class="secret-note" :title="t('admin.fieldTypesHint')" /><el-form-item :label="t('common.capabilitiesJson')"><el-input v-model="capabilitiesText" class="json-editor" type="textarea" spellcheck="false" /></el-form-item><el-form-item :label="t('admin.structurePreview')"><div class="capability-tags"><el-tag v-for="field in parsedFields" :key="field.key" effect="plain">{{ field.label }} · {{ field.type }}</el-tag><span v-if="!parsedFields.length" class="muted">{{ t('admin.noDynamicFields') }}</span></div></el-form-item></div></section></div><div class="editor-footer"><el-button @click="$router.push('/admin/platforms')">{{ t('common.cancel') }}</el-button><el-button type="primary" :loading="saving" @click="save">{{ t('admin.savePlatform') }}</el-button></div></el-form></template></DataState>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'; import { useRoute, useRouter } from 'vue-router'; import { ElMessage, type FormInstance, type FormRules } from 'element-plus'; import PageHeader from '@/components/PageHeader.vue'; import DataState from '@/components/DataState.vue'; import { createPlatform, getAdminPlatform, updatePlatform } from '@/api/platforms'; import type { PlatformCapabilityField, PublishPlatformInput } from '@/types/platform'; import { getErrorMessage } from '@/utils/errors'
import { useI18n } from 'vue-i18n'
type FormModel = { name: string; code: string; adapter_type: string; api_base_url: string; description: string; enabled: boolean }
const route = useRoute(); const router = useRouter(); const id = String(route.params.id); const isNew = computed(() => id === 'new'); const loading = ref(!isNew.value); const saving = ref(false); const error = ref(''); const formRef = ref<FormInstance>()
const { t } = useI18n()
const form = reactive<FormModel>({ name: '', code: '', adapter_type: '', api_base_url: '', description: '', enabled: true }); const capabilitiesText = ref(JSON.stringify({ supports_cover: true, fields: [{ key: 'caption', label: t('publish.commonDescription'), type: 'textarea', required: false, max_length: 1000 }] }, null, 2))
const rules = computed<FormRules<FormModel>>(() => ({ name: [{ required: true, message: t('admin.platformNameRequired'), trigger: 'blur' }], code: [{ required: true, message: t('admin.platformCodeRequired'), trigger: 'blur' }], adapter_type: [{ required: true, message: t('admin.adapterTypeRequired'), trigger: 'blur' }] }))
const parsedFields = computed<PlatformCapabilityField[]>(() => { try { const value = JSON.parse(capabilitiesText.value) as { fields?: PlatformCapabilityField[] }; return Array.isArray(value.fields) ? value.fields : [] } catch { return [] } })
function payload(): PublishPlatformInput { let capabilities: PublishPlatformInput['capabilities']; try { capabilities = JSON.parse(capabilitiesText.value) as PublishPlatformInput['capabilities'] } catch { throw new Error(t('admin.capabilitiesJsonInvalid')) } if (capabilities.fields && !Array.isArray(capabilities.fields)) throw new Error(t('admin.capabilitiesFieldsArray')); return { ...form, capabilities } }
async function load() { if (isNew.value) { loading.value = false; return } loading.value = true; error.value = ''; try { const item = await getAdminPlatform(id); Object.assign(form, { name: item.name, code: item.code, adapter_type: item.adapter_type ?? '', api_base_url: item.api_base_url ?? '', description: item.description ?? '', enabled: item.enabled }); capabilitiesText.value = JSON.stringify(item.capabilities ?? {}, null, 2) } catch (reason) { error.value = getErrorMessage(reason, t('admin.platformConfigLoadFailed')) } finally { loading.value = false } }
async function save() { if (!(await formRef.value?.validate().catch(() => false))) return; saving.value = true; try { const body = payload(); if (isNew.value) await createPlatform(body); else await updatePlatform(id, body); ElMessage.success(t('admin.platformSaved')); router.push('/admin/platforms') } catch (reason) { ElMessage.error(getErrorMessage(reason, t('admin.platformSaveFailed'))) } finally { saving.value = false } }
onMounted(load)
</script>

<style scoped>.editor-footer { display: flex; justify-content: flex-end; gap: 10px; margin-top: 20px; padding: 18px 0; }</style>
