<template>
  <div>
    <PageHeader eyebrow="Platform configuration" :title="isNew ? '新增发布平台' : '编辑发布平台'" description="capabilities 决定发布页动态呈现哪些平台字段。"><template #actions><el-button @click="$router.push('/admin/platforms')">返回平台列表</el-button></template></PageHeader>
    <DataState :loading="loading" :error="error" @retry="load"><template #content><el-form ref="formRef" :model="form" :rules="rules" label-position="top"><div class="content-grid"><section class="surface"><div class="surface-header"><div><h2>平台信息</h2><p>标识、适配器与服务地址</p></div></div><div class="surface-body"><div class="form-grid"><el-form-item label="平台名称" prop="name"><el-input v-model="form.name" /></el-form-item><el-form-item label="平台编码" prop="code"><el-input v-model="form.code" class="mono" /></el-form-item><el-form-item label="Adapter Type" prop="adapter_type"><el-input v-model="form.adapter_type" class="mono" /></el-form-item><el-form-item label="状态"><el-switch v-model="form.enabled" active-text="启用" inactive-text="停用" /></el-form-item><el-form-item label="API Base URL" class="span-2"><el-input v-model="form.api_base_url" /></el-form-item><el-form-item label="平台说明" class="span-2"><el-input v-model="form.description" type="textarea" :rows="4" /></el-form-item></div></div></section><section class="surface"><div class="surface-header"><div><h2>字段能力</h2><p>后端返回后，发布页按此结构动态渲染</p></div></div><div class="surface-body"><el-alert type="info" :closable="false" show-icon class="secret-note" title="fields 支持 text、textarea、tags、boolean、select、number。" /><el-form-item label="Capabilities JSON"><el-input v-model="capabilitiesText" class="json-editor" type="textarea" spellcheck="false" /></el-form-item><el-form-item label="结构预览"><div class="capability-tags"><el-tag v-for="field in parsedFields" :key="field.key" effect="plain">{{ field.label }} · {{ field.type }}</el-tag><span v-if="!parsedFields.length" class="muted">暂无动态字段</span></div></el-form-item></div></section></div><div class="editor-footer"><el-button @click="$router.push('/admin/platforms')">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存平台</el-button></div></el-form></template></DataState>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'; import { useRoute, useRouter } from 'vue-router'; import { ElMessage, type FormInstance, type FormRules } from 'element-plus'; import PageHeader from '@/components/PageHeader.vue'; import DataState from '@/components/DataState.vue'; import { createPlatform, getAdminPlatform, updatePlatform } from '@/api/platforms'; import type { PlatformCapabilityField, PublishPlatformInput } from '@/types/platform'; import { getErrorMessage } from '@/utils/errors'
type FormModel = { name: string; code: string; adapter_type: string; api_base_url: string; description: string; enabled: boolean }
const route = useRoute(); const router = useRouter(); const id = String(route.params.id); const isNew = computed(() => id === 'new'); const loading = ref(!isNew.value); const saving = ref(false); const error = ref(''); const formRef = ref<FormInstance>()
const form = reactive<FormModel>({ name: '', code: '', adapter_type: '', api_base_url: '', description: '', enabled: true }); const capabilitiesText = ref(JSON.stringify({ supports_cover: true, fields: [{ key: 'caption', label: '平台文案', type: 'textarea', required: false, max_length: 1000 }] }, null, 2))
const rules: FormRules<FormModel> = { name: [{ required: true, message: '请输入平台名称', trigger: 'blur' }], code: [{ required: true, message: '请输入平台编码', trigger: 'blur' }], adapter_type: [{ required: true, message: '请输入适配器类型', trigger: 'blur' }] }
const parsedFields = computed<PlatformCapabilityField[]>(() => { try { const value = JSON.parse(capabilitiesText.value) as { fields?: PlatformCapabilityField[] }; return Array.isArray(value.fields) ? value.fields : [] } catch { return [] } })
function payload(): PublishPlatformInput { let capabilities: PublishPlatformInput['capabilities']; try { capabilities = JSON.parse(capabilitiesText.value) as PublishPlatformInput['capabilities'] } catch { throw new Error('Capabilities 必须是有效 JSON') } if (capabilities.fields && !Array.isArray(capabilities.fields)) throw new Error('Capabilities.fields 必须是数组'); return { ...form, capabilities } }
async function load() { if (isNew.value) { loading.value = false; return } loading.value = true; error.value = ''; try { const item = await getAdminPlatform(id); Object.assign(form, { name: item.name, code: item.code, adapter_type: item.adapter_type ?? '', api_base_url: item.api_base_url ?? '', description: item.description ?? '', enabled: item.enabled }); capabilitiesText.value = JSON.stringify(item.capabilities ?? {}, null, 2) } catch (reason) { error.value = getErrorMessage(reason, '平台配置加载失败') } finally { loading.value = false } }
async function save() { if (!(await formRef.value?.validate().catch(() => false))) return; saving.value = true; try { const body = payload(); if (isNew.value) await createPlatform(body); else await updatePlatform(id, body); ElMessage.success('平台配置已保存'); router.push('/admin/platforms') } catch (reason) { ElMessage.error(getErrorMessage(reason, '平台保存失败')) } finally { saving.value = false } }
onMounted(load)
</script>

<style scoped>.editor-footer { display: flex; justify-content: flex-end; gap: 10px; margin-top: 20px; padding: 18px 0; }</style>
