<template>
  <div>
    <PageHeader :eyebrow="t('admin.eyebrow')" :title="t('admin.platformsTitle')" :description="t('admin.platformsIntro')"><template #actions><el-button type="primary" @click="$router.push('/admin/platforms/new')"><el-icon><Plus /></el-icon>{{ t('admin.addPlatform') }}</el-button></template></PageHeader>
    <section class="surface"><div class="toolbar"><div class="toolbar-group"><el-input v-model="keyword" clearable :placeholder="t('admin.searchPlatform')" :prefix-icon="Search" style="width: 250px" @keyup.enter="applySearch" @clear="applySearch" /><el-button @click="applySearch">{{ t('common.search') }}</el-button></div><span class="muted">{{ t('admin.totalPlatforms', { count: total }) }}</span></div>
      <DataState :loading="loading" :error="error" :empty="!platforms.length" :empty-text="t('admin.noPlatforms')" @retry="load"><el-button type="primary" @click="$router.push('/admin/platforms/new')">{{ t('admin.addPlatform') }}</el-button><template #content><el-table :data="platforms"><el-table-column :label="t('common.platform')" min-width="210"><template #default="scope"><div class="platform-cell"><span class="platform-glyph">{{ scope.row.name.slice(0, 1).toUpperCase() }}</span><div><div class="item-title">{{ scope.row.name }}</div><div class="item-meta mono">{{ scope.row.code }}</div></div></div></template></el-table-column><el-table-column prop="adapter_type" :label="t('admin.adapter')" min-width="150"><template #default="scope"><span class="mono">{{ scope.row.adapter_type || '—' }}</span></template></el-table-column><el-table-column :label="t('admin.dynamicFields')" min-width="150"><template #default="scope">{{ t('admin.fieldCount', { count: scope.row.capabilities.fields?.length ?? 0 }) }}</template></el-table-column><el-table-column :label="t('common.account')" min-width="100"><template #default="scope">{{ scope.row.accounts?.length ?? '—' }}</template></el-table-column><el-table-column :label="t('common.status')" width="100"><template #default="scope"><el-switch v-model="scope.row.enabled" :loading="switchingId === scope.row.id" @change="toggle(scope.row)" /></template></el-table-column><el-table-column :label="t('common.actions')" width="160" fixed="right"><template #default="scope"><el-button text type="primary" @click="$router.push(`/admin/platforms/${scope.row.id}`)">{{ t('common.configure') }}</el-button><el-button text type="danger" @click="remove(scope.row)">{{ t('common.delete') }}</el-button></template></el-table-column></el-table></template></DataState>
      <div v-if="total > pageSize" class="pagination-row"><el-pagination v-model:current-page="page" :page-size="pageSize" :total="total" layout="prev, pager, next" @current-change="load" /></div>
    </section>
  </div>
</template>

<script setup lang="ts">
import { onMounted, ref } from 'vue'; import { Plus, Search } from '@element-plus/icons-vue'; import { ElMessage, ElMessageBox } from 'element-plus'; import PageHeader from '@/components/PageHeader.vue'; import DataState from '@/components/DataState.vue'; import { deletePlatform, getAdminPlatforms, updatePlatform } from '@/api/platforms'; import type { PublishPlatform } from '@/types/platform'; import { getErrorMessage } from '@/utils/errors'
import { useI18n } from 'vue-i18n'
const platforms = ref<PublishPlatform[]>([]); const loading = ref(true); const error = ref(''); const keyword = ref(''); const page = ref(1); const pageSize = 20; const total = ref(0); const switchingId = ref('')
const { t } = useI18n()
async function load() { loading.value = true; error.value = ''; try { const result = await getAdminPlatforms({ page: page.value, page_size: pageSize, keyword: keyword.value || undefined }); platforms.value = result.items; total.value = result.total } catch (reason) { error.value = getErrorMessage(reason, t('admin.platformListFailed')) } finally { loading.value = false } }
function applySearch() { page.value = 1; load() }
async function toggle(platform: PublishPlatform) { switchingId.value = platform.id; try { await updatePlatform(platform.id, { enabled: platform.enabled }); ElMessage.success(t('admin.platformStatusUpdated')) } catch (reason) { platform.enabled = !platform.enabled; ElMessage.error(getErrorMessage(reason, t('admin.statusUpdateFailed'))) } finally { switchingId.value = '' } }
async function remove(platform: PublishPlatform) { try { await ElMessageBox.confirm(t('admin.deletePlatformPrompt', { name: platform.name }), t('admin.deletePlatformTitle'), { type: 'warning', confirmButtonText: t('common.confirmDelete'), cancelButtonText: t('common.cancel') }); await deletePlatform(platform.id); ElMessage.success(t('admin.platformDeleted')); await load() } catch (reason) { if (reason !== 'cancel' && reason !== 'close') ElMessage.error(getErrorMessage(reason, t('video.deleteFailed'))) } }
onMounted(load)
</script>

<style scoped>.platform-cell { display: flex; gap: 11px; align-items: center; }</style>
