upstream tbpub_bg {
    server 192.168.10.143:8000 max_fails=1 fail_timeout=10s;
}

server {
    listen 80;

    server_name tbpub.terabox.co.jp;
    server_name pub.u88.pub;

    access_log /var/log/nginx/tbpub.access.log main;

    client_max_body_size 50M;

    location / {
        root /home/user/tbpub/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /api {
        proxy_redirect off;

        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_http_version 1.1;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";

        proxy_pass http://tbpub_bg;
    }

    error_page 500 502 503 504 /50x.html;

    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
