import type { AppLocaleMessages } from './zh-CN'

const jaJP: AppLocaleMessages = {
  locale: { label: '言語', zhCN: '中文', jaJP: '日本語', enUS: 'English', saveFailed: '言語設定を保存できませんでした' },
  common: {
    save: '保存', cancel: 'キャンセル', delete: '削除', edit: '編集', configure: '設定', actions: '操作', status: '状態', enabled: '有効', disabled: '無効',
    search: '検索', filter: '絞り込み', reload: '再読み込み', back: '戻る', download: 'ダウンロード', publish: '公開', retry: '再試行', details: '詳細', result: '結果', time: '時間',
    platform: 'プラットフォーム', account: 'アカウント', video: '動画', user: 'ユーザー', model: 'モデル', description: '説明', name: '名前', code: 'コード', system: 'システム',
    success: '成功', failed: '失敗', open: '開く', copy: 'コピー', notConfigured: '未設定', notSet: '未設定', defaultAccount: 'デフォルトアカウント', untitledVideo: '無題の動画',
    noData: 'データがありません', dataUnavailable: 'データを一時的に利用できません', total: '全 {count} 件', seconds: '{count} 秒', currentValueKeep: '現在値：{value}。空欄なら変更しません',
    leaveBlankKeep: '空欄の場合は現在の値を変更しません', jsonInvalid: '有効な JSON である必要があります', confirmDelete: '削除を確認', close: '閉じる', select: '選択してください', addByEnter: '入力後 Enter で追加',
    prompt: 'プロンプト', adapterType: 'アダプタータイプ', modelId: 'モデル ID', apiBaseUrl: 'API ベース URL', apiKey: 'API キー', capabilitiesJson: '機能設定 JSON', clientId: 'クライアント ID', clientSecret: 'クライアントシークレット', accessToken: 'アクセストークン', refreshToken: 'リフレッシュトークン',
  },
  routes: { login: 'ログイン', forbidden: 'アクセス権限なし', dashboard: 'ダッシュボード', createVideo: '動画制作', videos: 'マイ動画', videoDetail: '動画詳細', publish: '動画公開', publishHistory: '公開履歴', publishResult: '公開結果', users: 'ユーザー管理', models: '動画モデル', modelConfig: 'モデル設定', platforms: '公開プラットフォーム', platformConfig: 'プラットフォーム設定', accounts: '公開アカウント', logs: '操作ログ', notFound: 'ページが見つかりません', workspace: 'ワークスペース' },
  nav: { workspace: '動画制作ワークスペース', apiMode: 'API 駆動モード', backendValidated: 'すべての操作をバックエンドで検証', creationAssets: '制作とアセット', publishManagement: '公開管理', systemManagement: 'システム管理', systemConfig: 'システム設定', openNavigation: 'ナビゲーションを開く', refresh: '現在のページを更新', logout: 'ログアウト' },
  role: { admin: '管理者', user: '一般ユーザー' },
  status: { pending: '待機中', processing: '処理中', publishing: '公開中', success: '成功', failed: '失敗', cancelled: 'キャンセル済み', timeout: 'タイムアウト', not_published: '未公開', partially_failed: '一部失敗', enabled: '有効', disabled: '無効', unknown: '不明' },
  generationType: { text_to_video: 'テキストから動画', image_to_video: '画像から動画' },
  auth: {
    kicker: 'エンタープライズ動画運用', headlineLine1: 'アイデアをすべての', headlineLine2: '公開先へ届ける。', intro: 'AI 動画制作、アセット管理、マルチプラットフォーム公開を一元化します。ログイン後、ロールに応じたワークスペースが開きます。',
    username: 'ユーザー名', password: 'パスワード', usernamePlaceholder: 'ユーザー名を入力', passwordPlaceholder: 'パスワードを入力', submit: 'ワークスペースにログイン', footnote: 'アカウントと権限は管理者が設定し、最終的な権限はサーバー側で検証されます。',
    visualAria: 'プラットフォーム機能概要', visualIntro: '生成タスクから公開結果まで、すべての操作を同じ追跡可能な制作フローで管理します。', production: '生成', assets: '動画アセット', channels: '公開先', tracked: 'タスクごとに追跡', managed: '一元管理', dynamic: '機能を動的に読み込み', workflowPrompt: 'プロンプト', workflowVideo: '動画', workflowPublish: '公開',
    tokenMissing: 'ログイン応答にアクセストークンがありません', loginFailed: 'ログインできません。ユーザー名とパスワードを確認してください', sessionExpired: 'セッションの有効期限が切れました。再度ログインしてください', forbiddenAction: 'この操作を行う権限がありません',
  },
  dashboard: {
    eyebrow: '概要', greetingMorning: 'おはようございます', greetingAfternoon: 'こんにちは', greetingEvening: 'こんばんは', greeting: '{greeting}、{name}', intro: '生成から公開まで、今日確認すべきタスクを表示します。', viewVideos: '動画を見る', createVideo: '動画を制作', recentVideos: '最近生成した動画', recentVideosHint: '直近で完了または処理中の動画アセット', allVideos: 'すべての動画', noVideos: '動画がありません。最初の生成タスクを作成してください', recentPublishes: '最近の公開履歴', recentPublishesHint: '各プラットフォームを個別タスクとして記録', allRecords: 'すべての履歴', noPublishes: '公開履歴はありません', partialLoadFailed: '一部のデータを読み込めませんでした。バックエンドサービスと API を確認してください。',
    metrics: { allVideos: '動画総数', myVideos: 'マイ動画', systemAssets: 'システム内の動画アセット', accountAssets: '現在のアカウントの動画アセット', todayTasks: '本日の生成タスク', submittedToday: '本日の送信数', generating: '生成中', generatingHint: '待機中または処理中のタスク', publishSuccess: '公開成功', recentRecords: '最近の履歴', publishFailed: '公開失敗', needsAttention: '確認が必要', users: 'ユーザー総数', usersHint: '登録済みシステムユーザー', tasks: 'タスク総数', tasksHint: '生成タスク合計' },
  },
  video: {
    createEyebrow: '制作', createTitle: '動画制作', createIntro: 'シーンを説明してください。参照画像を追加すると、画像から動画として自動処理されます。', backToMine: 'マイ動画へ戻る', content: '制作内容', contentHint: '被写体、環境、カメラ、動きを詳しく書くと安定します。', prompt: '動画の説明', promptOptional: '動画の説明（任意）', promptPlaceholder: '例：雨上がりの東京の通り。カメラは路面に沿ってゆっくり進み、ネオンの反射が車の流れとともに揺れる…', referenceOptional: '参照画像（任意）', referencePreviewAlt: '選択した参照画像のプレビュー', removeReference: '参照画像を削除', chooseReference: '参照画像を選択', referenceTip: 'JPG、PNG、WebP。上限は設定またはモデル機能に従います', generate: '動画を生成', settings: '生成設定', settingsHint: '現在のモデルから動的に提供されるオプション', generationModel: '動画生成モデル', selectModel: '有効なモデルを選択', duration: '動画の長さ', aspectRatio: 'アスペクト比', selectRatio: '比率を選択', resolution: '解像度', selectResolution: '解像度を選択', imageModeHint: '参照画像が追加されました。画像から動画として処理します。', textModeHint: '参照画像がないため、テキストから動画として処理します。', generationTask: '生成タスク', viewResult: '生成結果を見る', promptRequired: '動画の説明を入力してください', minPrompt: '3 文字以上入力してください', maxPrompt: '動画の説明は {count} 文字以内で入力してください', taskPending: 'タスクを送信しました。生成リソースを待っています。', taskProcessing: '動画を生成中です。実際の進捗がない場合、パーセントは表示しません。', taskSuccess: '動画を生成しました。結果を確認できます。', taskFailed: '生成に失敗しました。エラー内容を確認して再試行してください。', taskCancelled: 'タスクはキャンセルされました。', taskTimeout: 'タスクがタイムアウトしました。', modelsLoadFailed: 'モデル一覧を読み込めませんでした', imageTypes: 'JPG、PNG、WebP のみ対応しています', imageLessThan: '画像サイズは {size} MB 未満にしてください', imageMax: '画像サイズは {size} MB 以下にしてください', modelNoImageSwitch: 'このモデルは画像から動画に対応していません。モデルを変更してください', selectGenerationModel: '動画生成モデルを選択してください', modelNoImage: 'このモデルは画像から動画に対応していません', modelNoText: 'このモデルはテキストから動画に対応していません', taskCreated: '生成タスクを作成しました', taskCreateFailed: '生成タスクを作成できませんでした', taskQueryFailed: 'タスク状態を取得できませんでした', regeneratePrefill: '「{title}」の生成設定を読み込みました。確認して新しいタスクを作成してください。', sourceLoadFailed: '元動画の設定を読み込めませんでした', libraryEyebrow: 'ライブラリ', libraryTitle: 'マイ動画', libraryIntro: '生成した動画アセットを管理し、プレビュー、ダウンロード、公開へ進めます。', searchPlaceholder: 'タイトルまたは説明を検索', generationStatus: '生成状態', card: 'カード', list: '一覧', totalVideos: '全 {count} 本', noMatches: '条件に一致する動画がありません', createFirst: '最初の動画を制作', viewDetail: '詳細を見る', regenerate: '再生成', generationMethod: '生成方式', createdAt: '作成日時', publishedAt: '公開日時', listLoadFailed: '動画一覧を読み込めませんでした', downloadFailed: '動画をダウンロードできませんでした', deleteTitle: '動画を削除', deleteConfirm: '「{title}」を削除すると復元できません。続行しますか？', deleted: '動画を削除しました', deleteFailed: '削除できませんでした', detailEyebrow: 'アセット詳細', detailIntro: '生成設定、動画ファイル、プラットフォーム公開履歴を確認します。', backToList: '一覧へ戻る', notFound: '動画が存在しないか削除されています', browserUnsupported: 'ブラウザーは動画再生に対応していません。', fileNotReady: '動画ファイルはまだ準備できていません', publishHistory: '公開履歴', publishHistoryHint: 'プラットフォームごとに個別タスクとして表示', noPublishHistory: 'この動画の公開履歴はありません', openLink: 'リンクを開く', generationInfo: '生成情報', generationInfoHint: 'バックエンドへ送信した生成条件', model: '動画モデル', dimensions: '動画サイズ', fileSize: 'ファイルサイズ', referenceImage: '参照画像', referenceAlt: '動画生成に使用した参照画像', detailLoadFailed: '動画詳細を読み込めませんでした',
  },
  publish: {
    eyebrow: '配信', title: '動画公開', intro: '複数の公開先を選んで一度に送信します。公開先ごとに独立したタスクを作成します。', viewHistory: '公開履歴を見る', content: '公開内容', contentHint: '共通内容はすべての公開先で使用されます', targetVideo: '対象動画', selectVideo: '公開する動画を選択', commonTitle: '共通タイトル', commonTitlePlaceholder: '各公開先で使用する既定タイトルを入力', commonDescription: '共通説明', commonDescriptionPlaceholder: '動画の説明または本文を入力', tags: 'タグ / ハッシュタグ', tagsPlaceholder: '入力後 Enter で追加', coverOptional: '共通カバー（任意）', chooseCover: 'カバーを選択', coverTip: 'JPG、PNG、WebP。対応可否は capabilities に従います。', currentTasks: '今回の公開タスク', independentStatuses: '公開先ごとの状態は互いに影響しません', allRecords: 'すべての履歴', openResult: '結果を開く', targetPlatforms: '公開先', targetPlatformsHint: '公開先ごとにアカウントを選択', selectedCount: '{count} 件選択済み', noPlatforms: '利用可能な公開先がありません', publishAccount: '公開アカウント', selectAccount: '有効なアカウントを選択', autoPublicUrl: '公開動画 URL を自動入力済み', overrideCommon: '共通内容を上書き', createTasks: '公開タスクを作成', videoRequired: '対象動画を選択してください', titleRequired: '共通タイトルを入力してください', loadFailed: '動画または公開先データを読み込めませんでした。バックエンドを確認してください。', coverTypes: 'カバーは JPG、PNG、WebP のみ対応しています', coverMax: 'カバーサイズは {size} MB 以下にしてください', platformRequired: '公開先を 1 つ以上選択してください', accountRequired: '{platform} の公開アカウントを選択してください', fieldRequired: '{platform} の「{field}」を入力してください', tasksCreated: '{count} 件の独立した公開タスクを作成しました', taskCreateFailed: '公開タスクを作成できませんでした', historyEyebrow: '配信履歴', historyTitle: '公開履歴', historyIntro: '公開先ごとに個別タスクの状態、応答、失敗理由を確認します。', searchPlaceholder: '動画またはアカウントを検索', allPlatforms: 'すべての公開先', allStatuses: 'すべての状態', startDate: '開始日', endDate: '終了日', rangeSeparator: '～', totalRecords: '全 {count} 件', noRecords: '条件に一致する公開履歴がありません', viewVideo: '動画を見る', publishAccountColumn: '公開アカウント', publishTime: '公開日時', openPublishPage: '公開ページを開く', openPlatformPage: 'プラットフォームページを開く', republish: '再公開', historyLoadFailed: '公開履歴を読み込めませんでした', retryCreated: '{platform} の再試行タスクを作成しました', retryFailed: '再公開できませんでした', receiptEyebrow: '公開証明', resultTitle: '公開結果', resultIntro: 'プラットフォーム応答、動画内容、この公開の一意 ID を確認します。', backHistory: '公開履歴へ戻る', viewSource: '元動画を見る', resultNotFound: '該当する公開結果がありません', missingVideoPath: 'この公開履歴には利用可能な動画パスがありません', accountLabel: 'アカウント：{account}', completedAt: '完了日時：{time}', receipt: 'プラットフォーム応答', relativePathHint: 'サイト内の相対パスを使用するため、デプロイ先ドメインに自動追従します。', taskId: 'タスク ID', internalPath: 'サイト内パス', videoPath: '動画パス', publishFailed: '公開失敗', resultLoadFailed: '公開結果を読み込めませんでした', postIdCopied: 'Post ID をコピーしました', copyFailed: 'コピーできませんでした。ID を手動で選択してください', typePost: '投稿', typeVideo: '動画', postId: '投稿 ID', containerId: 'コンテナ ID', uploadId: 'アップロード ID', fieldVideoUrl: '公開動画 URL', fieldCaption: 'プラットフォーム本文', fieldShareToFeed: 'フィードにもシェア',
    viewPublishedContent: '公開内容を見る',
    openPlatformHome: 'プラットフォームのホームを開く',
  },
  admin: {
    youtubeChannelHandle: 'YouTube チャンネル名', youtubeChannelHandlePlaceholder: "例：{'@'}Qiao-f7p またはチャンネル URL", youtubeChannelHandleRequired: "有効な YouTube チャンネル名（例：{'@'}Qiao-f7p）を入力してください",
    eyebrow: 'システム管理', usersTitle: 'ユーザー管理', usersIntro: 'システムアカウント、ロール、有効状態を管理します。最終的なロール検証はバックエンドで行います。', addUser: 'ユーザー追加', searchUser: 'ユーザー名またはメールを検索', totalUsers: '全 {count} ユーザー', noUsers: 'ユーザーがいません', email: 'メール', role: 'ロール', lastLogin: '最終ログイン', resetPassword: 'パスワード再設定', editUser: 'ユーザー編集', displayName: '表示名', initialPassword: '初期パスワード', accountStatus: 'アカウント状態', usernameRequired: 'ユーザー名を入力してください', roleRequired: 'ロールを選択してください', passwordMin: 'パスワードは 8 文字以上必要です', userListFailed: 'ユーザー一覧を読み込めませんでした', userSaved: 'ユーザーを保存しました', userSaveFailed: 'ユーザーを保存できませんでした', userEnabled: 'ユーザーを有効にしました', userDisabled: 'ユーザーを無効にしました', statusUpdateFailed: '状態を更新できませんでした', resetPasswordPrompt: '@{username} の新しいパスワードを設定', resetPasswordConfirm: '再設定を確認', passwordReset: 'パスワードを再設定しました', passwordResetFailed: 'パスワードを再設定できませんでした', deleteUserPrompt: 'ユーザー @{username} を削除しますか？この操作は取り消せません。', deleteUserTitle: 'ユーザー削除', userDeleted: 'ユーザーを削除しました',
    modelsTitle: '動画モデル', modelsIntro: 'モデル機能により、制作ページで利用可能な時間、比率、解像度が決まります。キーは平文表示しません。', addModel: 'モデル追加', searchModel: '名前、コード、プロバイダーを検索', totalModels: '全 {count} モデル', noModels: '動画モデルが未設定です', provider: 'プロバイダー', capabilities: '生成機能', modelStatusUpdated: 'モデル状態を更新しました', deleteModelPrompt: 'モデル「{name}」を削除しますか？', deleteModelTitle: 'モデル削除', modelDeleted: 'モデルを削除しました', modelListFailed: 'モデル一覧を読み込めませんでした', addModelTitle: '動画モデル追加', editModelTitle: '動画モデル編集', modelEditorIntro: '接続情報とモデル機能はバックエンドのアダプターが使用し、フロントエンドからプロバイダーへ直接接続しません。', backModelList: 'モデル一覧へ戻る', connection: '基本・接続情報', secretHint: 'Secret が空欄の場合は既存値を変更しません', secretNotice: '機密フィールドはマスク表示のみで、完全な値は取得 API から返しません。', modelName: 'モデル名', modelCode: 'モデルコード', timeoutSeconds: 'タイムアウト（秒）', modelDescription: '説明', modelCapabilities: 'モデル機能', capabilitiesHint: 'この設定が動画制作フォームを動的に制御します', generationMethods: '生成方式', durationsCsv: '対応時間（秒、カンマ区切り）', ratiosCsv: '対応比率（カンマ区切り）', resolutionsCsv: '対応解像度（カンマ区切り）', maxImages: '参照画像上限', maxImageSize: '画像サイズ上限（MB）', extraJson: 'その他設定（JSON）', saveModel: 'モデルを保存', inputApiKey: 'API Key を入力', modelNameRequired: 'モデル名を入力してください', modelCodeRequired: 'モデルコードを入力してください', providerRequired: 'モデルプロバイダーを入力してください', adapterRequired: 'Adapter Type を入力してください', modelConfigLoadFailed: 'モデル設定を読み込めませんでした', generationMethodRequired: '生成方式を 1 つ以上有効にしてください', modelSaved: 'モデル設定を保存しました', modelSaveFailed: 'モデルを保存できませんでした',
    platformsTitle: '公開プラットフォーム', platformsIntro: 'アダプターと動的フィールド機能を設定します。公開ページはプラットフォームルールを固定実装しません。', addPlatform: 'プラットフォーム追加', searchPlatform: 'プラットフォーム名またはコードを検索', totalPlatforms: '全 {count} プラットフォーム', noPlatforms: '公開プラットフォームが未設定です', adapter: 'アダプター', dynamicFields: '動的フィールド', fieldCount: '{count} フィールド', platformListFailed: 'プラットフォーム一覧を読み込めませんでした', platformStatusUpdated: 'プラットフォーム状態を更新しました', deletePlatformPrompt: 'プラットフォーム「{name}」を削除しますか？関連アカウントは公開できなくなる場合があります。', deletePlatformTitle: 'プラットフォーム削除', platformDeleted: 'プラットフォームを削除しました', addPlatformTitle: '公開プラットフォーム追加', editPlatformTitle: '公開プラットフォーム編集', platformEditorIntro: 'capabilities に基づいて公開ページのフィールドを動的に表示します。', backPlatformList: 'プラットフォーム一覧へ戻る', platformInfo: 'プラットフォーム情報', platformInfoHint: '識別子、アダプター、サービス URL', platformName: 'プラットフォーム名', platformCode: 'プラットフォームコード', platformDescription: 'プラットフォーム説明', fieldCapabilities: 'フィールド機能', fieldCapabilitiesHint: 'バックエンドの構造に従って公開ページを動的に描画します', fieldTypesHint: 'fields は text、textarea、tags、boolean、select、number に対応します。', structurePreview: '構造プレビュー', noDynamicFields: '動的フィールドなし', savePlatform: 'プラットフォームを保存', platformNameRequired: 'プラットフォーム名を入力してください', platformCodeRequired: 'プラットフォームコードを入力してください', adapterTypeRequired: 'アダプタータイプを入力してください', capabilitiesJsonInvalid: 'Capabilities は有効な JSON である必要があります', capabilitiesFieldsArray: 'Capabilities.fields は配列である必要があります', platformConfigLoadFailed: 'プラットフォーム設定を読み込めませんでした', platformSaved: 'プラットフォーム設定を保存しました', platformSaveFailed: 'プラットフォームを保存できませんでした',
    accountsTitle: '公開アカウント', accountsIntro: 'プラットフォームごとに複数の公開アカウントを設定できます。Secret が空欄なら既存値を保持します。', addAccount: 'アカウント追加', searchAccount: 'アカウント名または識別子を検索', totalAccounts: '全 {count} アカウント', noAccounts: '公開アカウントが未設定です', accountIdentifier: 'アカウント識別子', tokenExpires: 'Token 有効期限', editAccount: '公開アカウント編集', addAccountTitle: '公開アカウント追加', secretKeepNotice: '機密フィールドは自動入力されません。空欄の場合は既存 Secret を変更しません。', accountName: 'アカウント名', instagramUserId: 'Instagram User ID（IG ユーザー ID）', instagramIdPlaceholder: '例：17841400000000000（@ユーザー名ではありません）', tokenExpiry: 'Token 有効期限', chooseExpiry: '有効期限を選択', oauthScopes: 'OAuth スコープ', oauthScopesPlaceholder: 'OAuth スコープを選択または入力', saveAccount: 'アカウントを保存', platformRequired: '公開プラットフォームを選択してください', accountNameRequired: 'アカウント名を入力してください', accountListFailed: 'アカウント一覧を読み込めませんでした', instagramIdRequired: 'Instagram User ID を入力してください（@ユーザー名ではありません）', accountSaved: '公開アカウントを保存しました', accountSaveFailed: 'アカウントを保存できませんでした', accountStatusUpdated: 'アカウント状態を更新しました', deleteAccountPrompt: '公開アカウント「{name}」を削除しますか？', deleteAccountTitle: 'アカウント削除', accountDeleted: 'アカウントを削除しました',
    logsTitle: '操作ログ', logsIntro: 'ログイン、生成、公開、システム設定操作の結果を読み取り専用で確認します。', searchLog: 'ユーザー、操作、リソース', allResults: 'すべての結果', totalLogs: '全 {count} ログ', noLogs: '条件に一致する操作ログがありません', actionType: '操作タイプ', resource: 'リソース', ip: 'IP', errorMessage: 'エラー情報', logsLoadFailed: '操作ログを読み込めませんでした',
  },
  statePage: { forbiddenTitle: '管理者権限が必要です', forbiddenText: '現在のアカウントではシステム設定にアクセスできません。管理操作はバックエンドでも個別に検証されます。', notFoundTitle: 'ページが見つかりません', notFoundText: 'URL が変更されたか、この機能はまだ利用できません。', backDashboard: 'ダッシュボードへ戻る' },
  errors: {
    requestFailed: 'リクエストに失敗しました。しばらくしてから再試行してください', businessFailed: '処理リクエストに失敗しました', timeout: 'リクエストがタイムアウトしました。サービス状態を確認してください', network: 'ネットワーク接続に失敗しました。バックエンドが起動しているか確認してください', uploadTooLarge: 'アップロードファイルが大きすぎます。10 MB 以下の画像を選択してください', INVALID_CREDENTIALS: 'ユーザー名またはパスワードが正しくありません', ACCOUNT_DISABLED: 'アカウントが存在しないか無効です', NOT_AUTHENTICATED: 'ログインしてください', INVALID_TOKEN: 'ログイン認証が無効または期限切れです', ADMIN_REQUIRED: 'この機能は管理者のみ利用できます', FORBIDDEN: 'このリソースへのアクセス権限がありません', MODEL_DISABLED: '選択した動画モデルは無効です', MODEL_ACCOUNT_DISABLED: '選択したモデルアカウントは無効です', MODEL_PROVIDER_DISABLED: '選択したモデルプロバイダーは無効です', TEXT_TO_VIDEO_UNSUPPORTED: '選択したモデルはテキストから動画に対応していません', IMAGE_TO_VIDEO_UNSUPPORTED: '選択したモデルは画像から動画に対応していません', INVALID_DURATIONS: '動画の長さは現在のモデルの許容範囲外です', INVALID_ASPECT_RATIOS: 'アスペクト比は現在の生成方式で利用できません', INVALID_RESOLUTIONS: '解像度は現在のモデルで利用できません', PROMPT_REQUIRED: '動画の説明を入力してください', PROMPT_TOO_LONG: '動画の説明がモデルの上限を超えています', INVALID_IMAGE_TYPE: '参照画像は JPG、PNG、WebP のみ対応しています', INVALID_IMAGE_CONTENT: '参照画像が無効です', PLATFORM_DISABLED: '選択した公開プラットフォームは無効です', ACCOUNT_PLATFORM_MISMATCH: '公開アカウントが選択したプラットフォームに属していません', PLATFORM_VIDEO_UNSUPPORTED: '選択したプラットフォームは動画公開に対応していません', PLATFORM_COVER_UNSUPPORTED: '選択したプラットフォームはカスタムカバーに対応していません', PLATFORM_FIELD_REQUIRED: 'プラットフォームの必須フィールドがありません', PLATFORM_FIELD_TOO_LONG: 'プラットフォームのフィールドが長すぎます', THIRD_PARTY_AUTH_FAILED: '外部サービスの認証に失敗しました', THIRD_PARTY_RATE_LIMITED: 'リクエストが多すぎます。しばらくしてから再試行してください', THIRD_PARTY_TIMEOUT: '外部サービスがタイムアウトしました', THIRD_PARTY_SERVICE_UNAVAILABLE: '外部サービスを一時的に利用できません', QUEUE_UNAVAILABLE: 'タスクキューを一時的に利用できません', REQUEST_VALIDATION_ERROR: 'リクエストパラメータが正しくありません', INTERNAL_ERROR: 'サーバー内部エラー', USER_EXISTS: 'ユーザー名またはメールは既に存在します', USER_NOT_FOUND: 'ユーザーが見つかりません', CANNOT_DELETE_SELF: '現在ログイン中のアカウントは削除できません', USER_HAS_RESOURCES: 'ユーザーに業務データがあるため、アカウントを無効にしてください', MODEL_NOT_FOUND: '動画モデルが見つかりません', VIDEO_NOT_FOUND: '動画が存在しないか削除されています', PUBLISH_TASK_NOT_FOUND: '公開タスクが見つかりません', PUBLISHED_POST_NOT_FOUND: '公開結果が見つかりません',
  },
}

export default jaJP
